# 🐍 GitHub Action: Gera uma "cobra" comendo seus commits no gráfico de contribuições
# Baseado no workflow de DanielAlexssander e otimizado para GitHub Actions v3+

name: Generate Snake

on:
  schedule:
    # Executa a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera o arquivo snake.svg e snake.gif
      - name: Generate GitHub contribution grid snake
        uses: Platane/snk@v3
        with:
          github_user_name: DanielAlexssander
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Mostra o status do repositório (debug)
      - name: Show status
        run: git status

      # Publica o resultado na branch "output"
      - name: Push generated snake files to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
